
import { useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import academicRules from '../data/academic/academic_rules.json'
import { courseKey, courseStatus, credits as courseCredits, getCourse, isInactiveCourse } from '../utils/coursePlanning'

const PROGRAM_TYPES = [
  { key: 'minor', label: '輔系', system: 'old' },
  { key: 'sub_minor', label: '輔修', system: 'new' },
  { key: 'second_major', label: '第二主修', system: 'new' },
  { key: 'double_major', label: '雙主修', system: 'old' },
]
const TYPE_META = Object.fromEntries(PROGRAM_TYPES.map((item) => [item.key, item]))

function norm(value) {
  return String(value || '').replace(/[\s（）()／/：:、，,\-—_]/g, '').toLowerCase()
}
function entryYear(profile = {}) {
  return Number(profile.applicationYear || profile.admissionYear || profile.entryYear || 115) || 115
}
function ruleVersionLabel(rule) {
  if (rule.autoGeneratedByUniversityRule) return '學校通則'
  if (rule.entryYearStart && rule.entryYearEnd && rule.entryYearStart !== rule.entryYearEnd) return `${rule.entryYearStart}-${rule.entryYearEnd}`
  if (rule.entryYearStart) return `${rule.entryYearStart}起`
  return '通用'
}
function courseName(course) {
  return String(getCourse(course).name || getCourse(course).course_name || '').trim()
}
function courseCode(course) {
  const c = getCourse(course)
  return String(c.code || c.course_code || c.courseCode || c.course_id || '').trim()
}
function courseDepartment(course) {
  const c = getCourse(course)
  return String(c.department || c.dept || c.major || c.unit || c.opening_unit || c.category || '').trim()
}
function programCourseCode(programCourse) {
  return String(programCourse?.code || programCourse?.course_code || programCourse?.courseCode || programCourse?.course_id || programCourse?.serial || '').trim()
}
function programCourseDepartment(programCourse) {
  return String(programCourse?.department || programCourse?.dept || programCourse?.unit || programCourse?.opening_unit || '').trim()
}
function departmentCompatible(programCourse, course) {
  const expected = programCourseDepartment(programCourse)
  if (!expected) return true
  const actual = courseDepartment(course)
  if (!actual) return false
  const a = norm(expected)
  const b = norm(actual)
  return b.includes(a) || a.includes(b)
}
function cleanTeacherName(value) {
  return String(value || '')
    .replace(/（[^）]*\*{2,}[^）]*）/g, '')
    .replace(/\([^)]*\*{2,}[^)]*\)/g, '')
    .replace(/\s*,\s*/g, '、')
    .replace(/\s+/g, ' ')
    .trim()
}

const SMART_SEARCH_ALIASES = [
  ['臺', '台'], ['裏', '裡'], ['祕', '秘'], ['羣', '群'], ['峯', '峰'], ['著', '着'],
  ['數位', '数字'], ['數據', '資料'], ['資料', '數據'], ['資訊', '信息'],
  ['實習', '實作'], ['實作', '實習'], ['概論', '導論'], ['導論', '概論'],
  ['程式', '程序'], ['影音', '影像'], ['媒體', '傳播'], ['人工智慧', 'AI'], ['ai', '人工智慧'],
]
const SMART_PHONETIC_ALIASES = [
  ['ying', 'ing'], ['in', 'ing'], ['en', 'eng'], ['an', 'ang'], ['z', 'zh'], ['c', 'ch'], ['s', 'sh'],
  ['ㄣ', 'ㄥ'], ['ㄢ', 'ㄤ'], ['ㄧㄣ', 'ㄧㄥ'], ['ㄓ', 'ㄗ'], ['ㄔ', 'ㄘ'], ['ㄕ', 'ㄙ'],
]
function toHalfWidth(value) {
  return String(value || '').replace(/[！-～]/g, (char) => String.fromCharCode(char.charCodeAt(0) - 0xFEE0)).replace(/　/g, ' ')
}
function normalizeSmartSearch(value) {
  let text = norm(toHalfWidth(value))
  SMART_SEARCH_ALIASES.forEach(([from, to]) => {
    text = text.replaceAll(norm(from), norm(to))
  })
  SMART_PHONETIC_ALIASES.forEach(([from, to]) => {
    text = text.replaceAll(from, to)
  })
  return text
}
function bigrams(value) {
  const text = normalizeSmartSearch(value)
  if (!text) return []
  if (text.length <= 2) return [text]
  return Array.from({ length: text.length - 1 }, (_, index) => text.slice(index, index + 2))
}
function fuzzyIncludesSmart(haystack, keyword) {
  const q = normalizeSmartSearch(keyword)
  if (!q) return true
  const target = normalizeSmartSearch(haystack)
  if (!target) return false
  if (target.includes(q) || q.includes(target)) return true
  const pieces = q.split(/\s+/).filter(Boolean)
  if (pieces.length > 1 && pieces.every((piece) => target.includes(piece))) return true
  const grams = bigrams(q)
  if (!grams.length) return false
  const hit = grams.filter((gram) => target.includes(gram)).length
  return q.length >= 4 && hit / grams.length >= 0.6
}

function offeringMatchesKeyword(offering, keyword) {
  const c = getCourse(offering)
  return fuzzyIncludesSmart(`${c.name || ''} ${c.serial || ''} ${c.code || ''} ${cleanTeacherName(c.teacher || c.instructor)} ${c.time_info || c.time || ''} ${c.classroom || c.room || c.location || ''}`, keyword)
}
function completedCoursePool(plan = {}) {
  return Object.values(plan || {}).flat().filter((course) => !isInactiveCourse(course))
}
function matchCourseByName(programCourse, course) {
  const target = norm(programCourse?.name)
  const actual = norm(courseName(course))
  if (!target || !actual) return false
  if (/本系|系選修|專業必修|專業選修|其他必修|其他選修|科目|課程/.test(programCourse?.name || '')) return false
  const expectedCode = programCourseCode(programCourse)
  if (expectedCode && courseCode(course) !== expectedCode) return false
  if (!expectedCode && !departmentCompatible(programCourse, course)) return false
  return target === actual || actual.includes(target) || target.includes(actual)
}
function isGenericProgramCourse(programCourse) {
  return /本系|系選修|專業必修|專業選修|其他必修|其他選修|科目|課程/.test(programCourse?.name || '')
}
function courseOfferingMatches(programCourse, course) {
  if (!programCourse || !course || isGenericProgramCourse(programCourse)) return false
  return matchCourseByName(programCourse, course)
}
function findCourseOfferings(programCourse, courses = []) {
  return (courses || []).filter((course) => courseOfferingMatches(programCourse, course))
}
function bestCourseOffering(programCourse, courses = []) {
  const matches = findCourseOfferings(programCourse, courses)
  return matches.sort((a, b) => String(getCourse(a).semester_source || getCourse(a).semester || '').localeCompare(String(getCourse(b).semester_source || getCourse(b).semester || '')))[0] || null
}
function isCandidateCourse(course, candidates = []) {
  if (!course) return false
  const key = courseKey(course)
  return Boolean(key) && (candidates || []).some((item) => !isInactiveCourse(item) && courseKey(item) === key)
}
function evaluateRule(rule, plan) {
  const pool = completedCoursePool(plan)
  const mandatory = rule?.courses?.mandatory || []
  const elective = rule?.courses?.elective || []
  const mandatoryDone = mandatory.filter((pc) => pool.some((course) => matchCourseByName(pc, course)))
  const electiveDone = elective.filter((pc) => pool.some((course) => matchCourseByName(pc, course)))
  const matchedNames = new Set([...mandatoryDone, ...electiveDone].map((item) => item.name))
  const matchedCredits = pool.reduce((sum, course) => {
    const hit = [...mandatory, ...elective].some((pc) => matchCourseByName(pc, course))
    return sum + (hit ? courseCredits(course) : 0)
  }, 0)
  const target = Number(rule?.requiredCredits || 0) || 0
  const current = Math.min(target || matchedCredits, matchedCredits || mandatoryDone.reduce((s, x) => s + Number(x.credits || 0), 0) + electiveDone.reduce((s, x) => s + Number(x.credits || 0), 0))
  const pct = target ? Math.min(100, Math.round((current / target) * 100)) : 0
  return { current, target, pct, matchedNames, mandatoryDone, electiveDone }
}
function baseKey(rule) {
  return `${rule.department}::${rule.track || ''}`
}
function departmentRequiredKey(group) {
  return `${group.department}::${group.track || ''}`
}
function departmentRequiredForGroup(group) {
  const table = academicRules.departmentRequiredCourses || {}
  return table[departmentRequiredKey(group)] || table[`${group.department}::`] || null
}
function selectionKey(item) {
  return `${item.department}::${item.track || ''}::${item.programType}`
}
function groupRules(programs = []) {
  const map = new Map()
  ;(programs || []).forEach((rule) => {
    const key = baseKey(rule)
    if (!map.has(key)) map.set(key, { department: rule.department, track: rule.track || '', rules: [] })
    map.get(key).rules.push(rule)
  })
  return [...map.values()].sort((a, b) => `${a.department}${a.track}`.localeCompare(`${b.department}${b.track}`, 'zh-Hant'))
}
function bestRule(rules, type, year) {
  const matches = (rules || []).filter((rule) => {
    if (rule.programType !== type) return false
    if (rule.entryYearStart && year < Number(rule.entryYearStart)) return false
    if (rule.entryYearEnd && year > Number(rule.entryYearEnd)) return false
    return true
  })
  return matches.sort((a, b) => Number(b.entryYearStart || 0) - Number(a.entryYearStart || 0))[0] || null
}
function makeDefaultRule(group, type, year) {
  const meta = TYPE_META[type]
  if (!meta) return null
  const oldTypes = group.rules.filter((r) => TYPE_META[r.programType]?.system === 'old')
  const newTypes = group.rules.filter((r) => TYPE_META[r.programType]?.system === 'new')
  const oldSupported = oldTypes.length > 0
  const newSupported = newTypes.length > 0
  if (meta.system === 'old' && !oldSupported) return null
  if (meta.system === 'new' && !newSupported) return null
  const defaults = academicRules.defaultRules || {}
  const base = defaults[type] || {}
  if (type === 'double_major') {
    const required = departmentRequiredForGroup(group)
    const courses = required?.courses || []
    const requiredCredits = required?.requiredCredits || base.requiredCredits || null
    return {
      id: `default_${type}_${group.department}_${group.track || 'main'}_${year}`,
      department: group.department,
      track: group.track || '',
      programType: type,
      requiredCredits,
      mandatoryCredits: requiredCredits || 0,
      electiveCredits: 0,
      autoGeneratedByUniversityRule: true,
      applicationYear: year,
      note: courses.length
        ? '雙主修通則：修讀該學系所有專業必修；本清單由主系必修資料暫算，仍以教務公告為準。'
        : '雙主修通則為修讀該學系所有專業必修，但目前缺少該系主系必修清單，暫時無法自動檢測課程。',
      courses: { mandatory: courses, elective: [] },
      rules: courses.length ? ['university_double_major_department_required'] : ['university_double_major_missing_required_courses'],
    }
  }
  const requiredCredits = base.requiredCredits || (type === 'second_major' ? 40 : type === 'sub_minor' ? 20 : 24)
  return {
    id: `default_${type}_${group.department}_${group.track || 'main'}_${year}`,
    department: group.department,
    track: group.track || '',
    programType: type,
    requiredCredits,
    mandatoryCredits: 0,
    electiveCredits: requiredCredits || 0,
    autoGeneratedByUniversityRule: true,
    applicationYear: year,
    note: base.note || '依學校通則執行，待取得系所正式科目表後覆蓋。',
    courses: { mandatory: [], elective: [] },
    rules: ['university_default_rule'],
  }
}
function getAvailableRule(group, type, year) {
  return bestRule(group.rules, type, year) || makeDefaultRule(group, type, year)
}
function systemOf(type) {
  return TYPE_META[type]?.system || ''
}
function selectedPrograms(profile = {}) {
  const list = profile.flexibleAcademicPrograms
  if (Array.isArray(list)) return list
  // Backward compatibility with old single-select object structure.
  const old = profile.academicPrograms || {}
  return Object.values(old).filter(Boolean)
}
function updateSelected(profile, onProfileChange, nextList) {
  onProfileChange?.((prev) => ({ ...(prev || profile || {}), flexibleAcademicPrograms: nextList }))
}
function ruleCardLabel(rule) {
  const track = rule.track ? `｜${rule.track}` : ''
  const req = rule.requiredCredits ? `${rule.requiredCredits}學分` : '依通則'
  return `${rule.department}${track}｜${TYPE_META[rule.programType]?.label || rule.programType}｜${req}`
}
function visibleRuleTypes(group, year) {
  return PROGRAM_TYPES.map((type) => ({ ...type, rule: getAvailableRule(group, type.key, year) })).filter((item) => Boolean(item.rule))
}
function courseTileClass(course, progress, kind) {
  const done = progress.matchedNames.has(course.name)
  return `myFlexCourseTile ${kind || ''} ${done ? 'done' : ''}`
}
function conflictMessage(selected, rule) {
  const conflict = selected.find((item) =>
    item.department === rule.department &&
    (item.track || '') === (rule.track || '') &&
    (item.programType || item.type) !== rule.programType
  )
  if (conflict) return `同一學系已選 ${TYPE_META[conflict.programType || conflict.type]?.label || conflict.programType}，不可再選其他學制。`
  return ''
}
function normalizeSelectedPrograms(list = []) {
  const map = new Map()
  ;(list || []).forEach((item) => {
    const key = `${item.department}::${item.track || ''}`
    if (!map.has(key)) map.set(key, item)
  })
  return [...map.values()]
}
function groupPickedProgram(selected, rule) {
  return selected.find((item) => item.department === rule.department && (item.track || '') === (rule.track || ''))
}
function buildSelection(rule) {
  return {
    type: rule.programType,
    programType: rule.programType,
    ruleId: rule.id,
    department: rule.department,
    track: rule.track || '',
    applicationYear: rule.applicationYear || rule.entryYearStart || '',
    requiredCredits: rule.requiredCredits || 0,
    mandatoryCredits: rule.mandatoryCredits || 0,
    electiveCredits: rule.electiveCredits || 0,
    autoGeneratedByUniversityRule: Boolean(rule.autoGeneratedByUniversityRule),
    note: rule.note || '',
    courses: rule.courses || { mandatory: [], elective: [] },
    rules: rule.rules || [],
  }
}

export default function FlexibleProgramsPage({ profile, onProfileChange, plan = {}, courses = [], candidates = [], onAddCandidate, onOpenCourseInfo }) {
  const [tab, setTab] = useState('explore')
  const [query, setQuery] = useState('')
  const [activeKey, setActiveKey] = useState('')
  const year = entryYear(profile)
  const groups = useMemo(() => groupRules(academicRules.programs || []), [])
  const selected = normalizeSelectedPrograms(selectedPrograms(profile))
  const filtered = groups.filter((group) => {
    const text = `${group.department} ${group.track || ''}`.toLowerCase()
    return !query.trim() || text.includes(query.trim().toLowerCase())
  })
  const active = groups.find((group) => baseKey(group) === activeKey) || filtered[0] || groups[0]
  const [offeringPicker, setOfferingPicker] = useState(null)
  const [offeringQuery, setOfferingQuery] = useState('')

  function openProgramCourse(programCourse) {
    const matches = findCourseOfferings(programCourse, courses)
    if (matches.length === 1) onOpenCourseInfo?.(matches[0])
    if (matches.length > 1) { setOfferingQuery(''); setOfferingPicker({ course: programCourse, matches }) }
  }

  function addProgramCourse(programCourse) {
    const matches = findCourseOfferings(programCourse, courses)
    if (matches.length === 1) onAddCandidate?.(matches[0])
    if (matches.length > 1) { setOfferingQuery(''); setOfferingPicker({ course: programCourse, matches }) }
  }

  function openOfferingPicker(programCourse) {
    const matches = findCourseOfferings(programCourse, courses)
    if (matches.length >= 1) { setOfferingQuery(''); setOfferingPicker({ course: programCourse, matches }) }
  }

  function renderOfferingPicker() {
    if (!offeringPicker) return null
    const programCourse = offeringPicker.course || {}
    const matches = (offeringPicker.matches || []).filter((offering) => offeringMatchesKeyword(offering, offeringQuery))
    const modal = <div className="flexOfferingModalBackdrop" onMouseDown={() => setOfferingPicker(null)}>
      <div className="flexOfferingModal" onMouseDown={(event) => event.stopPropagation()}>
        <header>
          <div>
            <span>選擇開課班別</span>
            <h3>{programCourse.name}</h3>
          </div>
          <button type="button" onClick={() => setOfferingPicker(null)}>×</button>
        </header>
        <div className="flexOfferingSearch">
          <input value={offeringQuery} onChange={(event) => setOfferingQuery(event.target.value)} placeholder="搜尋序號、教師、時間、教室" autoFocus />
          <small>{matches.length}/{offeringPicker.matches?.length || 0} 筆</small>
        </div>
        <div className="flexOfferingList">
          {matches.length ? matches.map((offering) => {
            const oc = getCourse(offering)
            const code = oc.serial || oc.code || oc.course_id || ''
            const teacher = cleanTeacherName(oc.teacher || oc.instructor) || '未列教師'
            const time = oc.time_info || oc.time || '未列時間'
            const room = oc.classroom || oc.room || oc.location || ''
            const inCandidate = isCandidateCourse(offering, candidates)
            return <article key={courseKey(offering)} className="flexOfferingRow">
              <div>
                <strong>{code || oc.name}</strong>
                <span>{teacher}</span>
                <small>{time}{room ? `｜${room}` : ''}</small>
              </div>
              <div>
                <button type="button" onClick={() => onOpenCourseInfo?.(offering)}>資訊</button>
                <button type="button" disabled={inCandidate} onClick={() => onAddCandidate?.(offering)}>{inCandidate ? '已暫存' : '+ 暫存'}</button>
              </div>
            </article>
          }) : <div className="emptyVariantBox"><b>找不到符合條件的班別</b></div>}
        </div>
      </div>
    </div>
    return createPortal(modal, document.body)
  }

  function toggleRule(rule) {
    if (!rule) return
    const key = selectionKey(rule)
    const exists = selected.some((item) => selectionKey(item) === key)
    let next = selected.filter((item) => selectionKey(item) !== key)
    if (!exists) {
      const msg = conflictMessage(selected, rule)
      if (msg) {
        window.alert(msg)
        return
      }
      next = [...next, buildSelection(rule)]
      if (next.length > 1) {
        // 規劃工具只提醒，不強制限制每次申請只能新增一個。
        console.info('UniPlan提醒：學校規定每次申請次學年度跨領域修讀以加選一個為限。')
      }
    }
    updateSelected(profile, onProfileChange, next)
  }

  return <section className="pageCard flexibleProgramsPage">
    <div className="flexHeader">
      <div><h2>彈性學制</h2><p>選擇科系與學制後，畢業學分會自動擴充對應進度條。可規劃多個科系，實際申請仍以教務公告為準。</p></div>
      <span>{profile?.department || '未綁定系所'}</span>
    </div>
    <div className="flexTabs">
      <button className={tab === 'explore' ? 'active' : ''} onClick={() => setTab('explore')}>探索學制</button>
      <button className={tab === 'mine' ? 'active' : ''} onClick={() => setTab('mine')}>我的學制 <b>{selected.length}</b></button>
    </div>

    {tab === 'explore' && <div className="flexLayout">
      <aside className="flexDeptList">
        <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜尋系所或組別" />
        <div>
          {filtered.map((group) => {
            const key = baseKey(group)
            const count = visibleRuleTypes(group, year).length
            return <button key={key} className={key === baseKey(active) ? 'active' : ''} onClick={() => setActiveKey(key)}>
              <strong>{group.department}</strong>
              <span>{group.track || '一般'}｜{count} 種學制</span>
            </button>
          })}
        </div>
      </aside>
      {active && <main className="flexRulePanel">
        <div className="flexRuleHead"><div><h3>{active.department}</h3>{active.track && <p>{active.track}</p>}</div><small>同系互斥原則｜依規則套用</small></div>
        <div className="flexTypeGrid">
          {visibleRuleTypes(active, year).map((item) => {
            const rule = item.rule
            const picked = selected.some((selectedRule) => selectionKey(selectedRule) === selectionKey(rule))
            const pickedInGroup = groupPickedProgram(selected, rule)
            const lockedBySameDept = Boolean(pickedInGroup && selectionKey(pickedInGroup) !== selectionKey(rule))
            return <button
              key={item.key}
              className={`flexTypeCard ${picked ? 'selected' : ''} ${lockedBySameDept ? 'locked' : ''}`}
              disabled={lockedBySameDept}
              onClick={() => toggleRule(rule)}
            >
              <b>{item.label}</b>
              <strong>{rule.requiredCredits ? `${rule.requiredCredits}學分` : '依學校通則'}</strong>
              <span>{picked ? '已加入我的學制' : lockedBySameDept ? `同系已選 ${TYPE_META[pickedInGroup.programType || pickedInGroup.type]?.label || '其他學制'}` : '點擊加入規劃'}</span>
            </button>
          })}
        </div>
        <p className="flexPolicyNote">互斥原則：同一學系若申請輔系或雙主修，不可再申請該系輔修或第二主修；反之亦然。取得資格後，通常須修讀滿一年後才能放棄。</p>
      </main>}
    </div>}

    {tab === 'mine' && <div className="myFlexPrograms">
      {selected.length === 0 && <div className="emptyState"><h3>尚未選擇彈性學制</h3><p>到「探索學制」選擇科系與學制後，這裡會列出所需學分與課程。</p></div>}
      {selected.map((item) => {
        const rule = (academicRules.programs || []).find((rule) => rule.id === item.ruleId) || item
        const progress = evaluateRule(rule, plan)
        return <article key={selectionKey(item)} className="myFlexCard">
          <header><div><h3>{ruleCardLabel(rule)}</h3><p>{rule.autoGeneratedByUniversityRule ? '依學校通則' : '已加入彈性學制規劃'}</p></div><button onClick={() => updateSelected(profile, onProfileChange, selected.filter((x) => selectionKey(x) !== selectionKey(item)))}>移除</button></header>
          <div className="myFlexProgress"><strong>{progress.current}/{progress.target || rule.requiredCredits || 0}</strong><span><i style={{ width: `${progress.pct}%` }} /></span><em>{progress.pct}%</em></div>
          <div className="myFlexCourseBlocks">
            {(rule.courses?.mandatory || []).length > 0 && <section><h4>必修 {rule.mandatoryCredits || 0}學分</h4><div className="myFlexCourseGrid">{(rule.courses?.mandatory || []).slice(0, 40).map((course) => {
              const matches = findCourseOfferings(course, courses)
              const offering = matches[0] || null
              const hasMultiple = matches.length > 1
              return <article key={course.name} className={courseTileClass(course, progress, 'required')}>
                <button type="button" className="myFlexCourseMain" disabled={!offering} onClick={() => openOfferingPicker(course)}>
                  <strong>{progress.matchedNames.has(course.name) ? '✓ ' : ''}{course.name}</strong>
                  <span>{course.credits ? `${course.credits}學分` : '課程'}{matches.length ? `｜${matches.length}班` : '｜未開課'}</span>
                </button>
              </article>
            })}</div></section>}
            {(rule.courses?.elective || []).length > 0 && <section><h4>選修 {rule.electiveCredits || 0}學分</h4><div className="myFlexCourseGrid">{(rule.courses?.elective || []).slice(0, 60).map((course) => {
              const matches = findCourseOfferings(course, courses)
              const offering = matches[0] || null
              const hasMultiple = matches.length > 1
              return <article key={course.name} className={courseTileClass(course, progress, 'elective')}>
                <button type="button" className="myFlexCourseMain" disabled={!offering} onClick={() => openOfferingPicker(course)}>
                  <strong>{progress.matchedNames.has(course.name) ? '✓ ' : ''}{course.name}</strong>
                  <span>{course.credits ? `${course.credits}學分` : '課程'}{matches.length ? `｜${matches.length}班` : '｜未開課'}</span>
                </button>
              </article>
            })}</div></section>}
            {(rule.courses?.mandatory || []).length === 0 && (rule.courses?.elective || []).length === 0 && <section className="myFlexDefaultRule"><h4>依學校通則</h4><p>{rule.programType === 'double_major' ? '雙主修通則為修讀該學系所有專業必修；目前缺少該系主系必修清單，因此暫時無法自動檢測課程。' : '此學制目前沒有科目表，UniPlan 只能先建立學分目標；實際可計入課程需由學生手動標記或待系所科目表補齊。'}</p></section>}
          </div>
          {rule.note && <p className="myFlexNote">{rule.note}</p>}
        </article>
      })}
    </div>}
    {renderOfferingPicker()}
  </section>
}
